CREATE schema REACTIVE_POSTGRES;

CREATE TABLE PURCHASE
(
    ID          VARCHAR(100),
    CUSTOMER_ID VARCHAR(100),
    AMOUNT      DECIMAL,
    DISCOUNT    DECIMAL
        CONSTRAINT PURCHASE_PK PRIMARY KEY (ID)
)