CREATE schema REACTIVE_POSTGRES;

CREATE TABLE PURCHASE IF NOT EXISTS
(
    ID          VARCHAR(100),
    CUSTOMER_ID VARCHAR(100),
    AMOUNT      DECIMAL,
    DISCOUNT    DECIMAL,
    CONSTRAINT PURCHASE_PK PRIMARY KEY (ID)
)

CREATE TABLE STOCK IF NOT EXISTS(
    PRODUCT_ID INTEGER,
    AMOUNT_AVAILABLE INTEGER,
    CONSTRAINT STOCK_PK PRIMARY KEY (PRODUCT_ID)
)